--- #YAML:1.0
name:               Math-Fractal-Noisemaker
version:            0.102
abstract:           ~
author:
    - Alex Ayars <pause@nodekit.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Tempdir:  0.02
    Imager:         0.7
    Math::Complex:  1.56
    Test::Simple:   0.86
    Tie::CArray:    0.15
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
